import json
import os

with open( "config/config.json", "r" ) as configFile :
	data = configFile.read( )

data = json.loads( data )

# APP VARS
APP_EMAIL = data['APP']['EMAIL']
APP_TOOL  = data['APP']['TOOL']

# DATABASE VARS
DB_HOST = data['DB']['DB_HOST']
DB_USER = data['DB']['DB_USER']
DB_PASS = data['DB']['DB_PASS']
DB_NAME = data['DB']['DB_NAME']
DB_STAGING = data['DB']['DB_STAGING']
DB_STATS = data['DB']['DB_STATS']
DB_QUICK = data['DB']['DB_QUICK']
DB_COMMIT_COUNT = data['DB']['DB_COMMIT_COUNT']

# PATHS
DOWNLOAD_DIR = data['PATHS']['DOWNLOAD_DIRECTORY'] + os.sep
EG_DIR = DOWNLOAD_DIR + data['PATHS']['ENTREZ_GENE_DIR'] + os.sep
GO_DIR = DOWNLOAD_DIR + data['PATHS']['GO_DIR'] + os.sep
UP_DIR = DOWNLOAD_DIR + data['PATHS']['UNIPROT_DIR'] + os.sep
PSI_DIR = DOWNLOAD_DIR + data['PATHS']['PSI_DIR'] + os.sep
SGD_DIR = DOWNLOAD_DIR + data['PATHS']['SGD_DIR'] + os.sep
CGD_DIR = DOWNLOAD_DIR + data['PATHS']['CGD_DIR'] + os.sep
POMBASE_DIR = DOWNLOAD_DIR + data['PATHS']['POMBASE_DIR'] + os.sep
REFSEQ_DIR = DOWNLOAD_DIR + data['PATHS']['REFSEQ_DIR'] + os.sep

# ENTREZ GENE FILES
EG_GENEHISTORY = EG_DIR + data['FILES']['EG_GENEHISTORY']
EG_GENEINFO = EG_DIR + data['FILES']['EG_GENEINFO']
EG_GENE2ACCESSION = EG_DIR + data['FILES']['EG_GENE2ACCESSION']
EG_GENE2REFSEQ = EG_DIR + data['FILES']['EG_GENE2REFSEQ']
EG_REFSEQ2UNIPROT = EG_DIR + data['FILES']['EG_REFSEQ2UNIPROT']
EG_GENE2GO = EG_DIR + data['FILES']['EG_GENE2GO']
EG_GROUPS = EG_DIR + data['FILES']['EG_GROUPS']
EG_GENE2ENSEMBL = EG_DIR + data['FILES']['EG_GENE2ENSEMBL']

# GO FILES
GO_DEFINITIONS = GO_DIR + data['FILES']['GO_DEFINITIONS']

# UNIPROT FILES
UP_SWISSPROT = UP_DIR + data['FILES']['UP_SWISSPROT']
UP_IDMAPPING = UP_DIR + data['FILES']['UP_IDMAPPING']
UP_TREMBL = UP_DIR + data['FILES']['UP_TREMBL']
UP_ISOFORMS = UP_DIR + data['FILES']['UP_ISOFORMS']
UP_PROTEINS_DIR = UP_DIR + data['PATHS']['UNIPROT_PROTEINS_DIR'] + os.sep 

# PSI FILES
PSI_DEFINITIONS = PSI_DIR + data['FILES']['PSI_DEFINITIONS']

# MODEL ORGANISM DATABASE FILES
SGD_FEATURES = SGD_DIR + data['FILES']['SGD_FEATURES']
CGD_FEATURES = CGD_DIR + data['FILES']['CGD_FEATURES']
POMBASE_FEATURES = POMBASE_DIR + data['FILES']['POMBASE_FEATURES']

# REFSEQ FILES
PROTEIN_DIR = REFSEQ_DIR + data['PATHS']['REFSEQ_PROTEIN_DIR'] + os.sep
RNA_DIR = REFSEQ_DIR + data['PATHS']['REFSEQ_RNA_DIR'] + os.sep
PROTEIN_MISSING_DIR = REFSEQ_DIR + data['PATHS']['REFSEQ_MISSING_PROTEIN_DIR'] + os.sep